#!/usr/bin/env python
# -*- coding: utf-8 -*-

1. __add__方法示例
class Vector(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __str__(self):
        return 'vector-(%d, %d)' %(self.a, self.b)

    def __add__(self, other):
        return Vector(self.a + other.a, self.b + other.b)

v1 = Vector(2, 10)
v2 = Vector(5, -2)
v3 = Vector(5, 2)

print v1 + v2 + v3

2. 操作mysql数据库示例
示例一:
import MySQLdb

db = MySQLdb.connect('192.168.0.1', 'root', 'xxxxxxx', 'test')

cursor = db.cursor()

cursor.execute('select version()')

data = cursor.fetchone()

print 'database version: %s' %data

db.close()
'-------'
示例二:
import MySQLdb

db = MySQLdb.connect('192.168.0.1', 'root', 'xxxxxxx', 'test')

cursor = db.cursor()

sql = '''
insert into employee (first_name, last_name, age, sex, income)
values ('mac', 'mohan', 20, 'm', 2000)
'''

try:
    cursor.execute(sql)
    db.commit()
except:
    db.rollback()

db.close()
'-------'
示例三:
import MySQLdb

db = MySQLdb.connect('192.168.0.1', 'root', 'xxxxxxx', 'test')

cursor = db.cursor()

sql = 'select * from employee where income > "%d"' %(1000)

try:
    cursor.execute(sql)
    results = cursor.fetchall()
    for row in results:
        fname = row[0]
        lname = row[1]
        age = row[2]
        sex = row[3]
        income = row[4]
        print 'fname=%s, lname=%s, age=%d, sex=%s, income=%d' %\
              (fname, lname, age, sex, income)
except:
    print 'error: unable to fetch data.'

db.close()
'-------'
示例四:
import MySQLdb

db = MySQLdb.connect('192.168.0.1', 'root', 'xxxxxxx', 'test')

cursor = db.cursor()

sql = 'select * from employee where income > "%d"' %(1000)

try:
    cursor.execute(sql)
    results = cursor.fetchall()
    print 'end is %s' %results
except:
    print 'error: unable to fetch data.'

db.close()
'-------'
示例五:
import MySQLdb

db = MySQLdb.connect('192.168.0.1', 'root', 'xxxxxxx', 'test')

cursor = db.cursor()

sql = 'update employee set age = age + 1 where sex = "%s"' %('m')

try:
    cursor.execute(sql)
    db.commit()
except:
    db.rollback()

db.close()
'-------'
示例六:
import MySQLdb

db = MySQLdb.connect('192.168.0.1', 'root', 'xxxxxxx', 'test')

cursor = db.cursor()

sql = 'delete from employee where age > "%d"' %(20)

try:
    cursor.execute(sql)
    db.commit()
except:
    db.rollback()

db.close()

3. socket通讯示例
服务端:
import socket

s = socket.socket()
host = socket.gethostname()
port = 12345
s.bind((host, port))

s.listen(5)
while True:
    c, addr = s.accept()
    print 'connection address: ', addr
    c.send('welcome! ')
    c.close()
'-------'
客户端:
import socket

s = socket.socket()          
host = socket.gethostname() 
port = 12345               

s.connect((host, port))
print s.recv(1024)
s.close()  

4. 发送邮件示例
import smtplib
from email.mime.text import MIMEText
from email.header import Header

mail_host = 'smtp.189.cn'
mail_user = 'xxxxxxx@189.cn'
mail_pwd = 'xxxxxxx'

sender = 'xxxxxxx@189.cn'
receivers = ['xxxxxxx@qq.com', 'xxxxxxx@163.com']

message = MIMEText('this is a test mail about python...', 'plain', 'utf-8')
message['From'] = Header('teacher', 'utf-8')
message['To'] = Header('test', 'utf-8')
message['Subject'] = Header('a python test mail', 'utf-8')

try:
    mail = smtplib.SMTP()
    mail.connect(mail_host, 25)
#   mail.set_debuglevel(1)
    mail.login(mail_user, mail_pwd)
    mail.sendmail(sender, receivers, message.as_string())
    print 'send success!'
except smtplib.SMTPException:
    print 'some error occoured!'

5. 装饰器示例
示例一:
def log(func):
    def wrapper(*args, **kw):
        print 'call %s():' % func.__name__
        return func(*args, **kw)
    return wrapper

@log
def now():
    print '2015-10-19'

now()
'-------'
示例二:
def makebold(fn):
    def wrapped():
        return "<b>" + fn() + "</b>"
    return wrapped
 
def makeitalic(fn):
    def wrapped():
        return "<i>" + fn() + "</i>"
    return wrapped
 
@makebold
@makeitalic
def hello():
    return "hello world"
 
print hello()
