#!/usr/bin/env python
# -*- coding: utf-8 -*-

1. __add__方法示例:
class Vector(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __str__(self):
        return 'vector-(%d, %d)' %(self.a, self.b)

    def __add__(self, other):
        return Vector(self.a + other.a, self.b + other.b)

v1 = Vector(2, 10)
v2 = Vector(5, -2)
v3 = Vector(5, 2)

print v1 + v2 + v3

2. 连接MySQL数据库并获取版本号示例:
import MySQLdb

db = MySQLdb.connect('192.168.10.155', 'root', 'clt!2016', 'test')

cursor = db.cursor()

cursor.execute('select version()')

data = cursor.fetchone()

print 'database version: %s' %data

db.close()

